<?php
namespace bot;
use bot\TModel;

class money extends RequestController
{

    public function processMessages()
    {
        parent::processMessages(); // TODO: Change the autogenerated stub
    }

}